apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-data
spec:
  capacity:
    storage: 70Gi
  accessModes:
    - ReadWriteMany
  storageClassName: mariadb-data
  nfs:
    # FIXME: use the right IP
    server: 10.40.0.6
    path: "/exports/mariadb/data"
