apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirror
  namespace: default
  labels:
    app: mirror
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mirror
  template:
    metadata:
      labels:
        app: mirror
        version: v1
    spec:
      containers:
      - name: mirror
        image: slzcc/nginx:language-zh
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
          - mountPath: "/etc/nginx/sites-available"
            name: config-volume
          - mountPath: "/mirror"
            name: mirror
      volumes:
        - name: config-volume
          configMap:
            name: mirror
            items:
            - key: default.conf
              path: default
        - hostPath:
            path: "/var/data/mirror"
          name: mirror
