apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-mirror
  namespace: default
  labels:
    app: cheese
    cheese: nginx-mirror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: nginx-mirror
  template:
    metadata:
      labels:
        app: cheese
        task: nginx-mirror
        version: v0.0.1
    spec:
      nodeSelector:
        role: shileizcc.com
      containers:
      - name: nginx-mirror
        image: registry.aliyuncs.com/slzcc/nginx:language-zh
        ports:
        - name: http
          containerPort: 80
        command: ["nginx", "-g", "daemon off;"]
        volumeMounts:
          - mountPath: "/etc/nginx/sites-available"
            name: config-volume
          - mountPath: "/mirror"
            name: mirror
      imagePullSecrets:
        - name: myregistrykey
      volumes:
        - name: config-volume
          configMap:
            name: nginx-mirror
              items:
              - key: default.conf
                path: default
        - hostPath:
            path: "/var/data/work_dir/mirror"
          name: mirror
