kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: etcd
#  namespace: kube-system
  labels:
    k8s-app: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: etcd
  template:
    metadata:
      labels:
        k8s-app: etcd
        name: etcd
        version: v1.0.0
    spec:
      containers:
      - image: etcd
        name: etcd
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 2379
        - name: https
          containerPort: 4001
        volumes:
        - name: data
          path: /var/lib/etcd
        args:
        - -listen-client-urls http://0.0.0.0:2379
        - -advertise-client-urls http://0.0.0.0:2379
