apiVersion: v1
kind: Pod
metadata:
#  namespace: kube-system
  name: confluence
  labels:
    name: confluence
    kubernetes.io/cluster-service: "true"
spec:
  containers:
  - name: confluence
    image: registry.aliyuncs.com/slzcc/confluence
    ports:
    - name: in
      containerPort: 8090
    - name: out
      containerPort: 8000
    volumeMounts:
      - mountPath: "/opt/altassian/confluence/data"
        name: data
  imagePullSecrets:
    - name: myregistrykey
  volumes:
    - hostPath:
        path: "/opt/altassian/confluence/data"
      name: data
