apiVersion: v1
kind: Service
metadata:
  name: confluence
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Confluence"
spec:
  clusterIP: None
  selector:
    name: confluence
  ports:
   - name: http
     port: 8090
     targetPort: 8090
     protocol: TCP
   - name: https
     port: 8000
     targetPort: 8000
     protocol: TCP
