apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      nodeSelector:
        role: shileizcc.com
      containers:
      - name: nfs-server
        image: registry.aliyuncs.com/slzcc/nfs-server
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: mypvc
#      volumes:
#        - name: mypvc
#          persistentVolumeClaim:
#            claimName: nfs-pv-provisioning-demo
      volumes:
      - name: mypvc
        hostPath:
          path: /var/data/nfs
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
