apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: jira-data
  nfs:
    # FIXME: use the right IP
    server: 10.32.0.10
    path: "/exports/jira-data"
