#apiVersion: v1
#kind: Endpoints
#metadata:
#  name: demo
#subsets:
#- addresses:
##  - ip: 47.95.219.151
#  ports:
#  - port: 80
#    protocol: TCP
#---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  ports:
  - name: http
    port: 80
#    targetPort: 80
  loadBalancerIP: 172.17.145.245
  type: LoadBalancer
#status:
#  loadBalancer:
#    ingress:
#    - ip: 47.95.219.151
