apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mirror-virtualservice
spec:
  hosts:
  - mirror.default
  http:
  - route:
    - destination:
        host: mirror.default.svc.cluster.local
        subset: v1

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mirror-destinationrule
spec:
  host: mirror.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1