apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mysql-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 3306
      name: tcp
      protocol: TCP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mysql-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - mysql
  tcp:
  - route:
    - destination:
        host: mysql
        port:
          number: 3306
        subset: v1

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mysql-destinationrule
spec:
  host: mysql
  subsets:
  - name: v1
    labels:
      version: v1