apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomexam
  namespace: default
  labels:
    app: cheese
    task: tomexam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: tomexam
  template:
    metadata:
      labels:
        app: cheese
        task: tomexam
        version: v0.0.1
    spec:
      nodeSelector:
        role: xsj
      containers:
      - name: tomexam
        image: registry.aliyuncs.com/slzcc/tomexam:3.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: TZ
          value: "Asia/Shanghai"
        volumeMounts:
          - mountPath: "/usr/local/tomcat/webapps/ROOT"
            name: data
        env:
        - name: TZ
          value: "Asia/Shanghai"
      imagePullSecrets:
        - name: myregistrykey
      volumes:
        - hostPath:
            path: "/data/tomexam/ROOT"
          name: data
      imagePullSecrets:
        - name: myregistrykey
