apiVersion: v1
kind: Service
metadata:
  name: tomexam
  namespace: default
spec:
  ports:
   - name: http
     port: 8080
     targetPort: 8080
     protocol: TCP
     nodePort: 58080
  type: NodePort
  selector:
    app: cheese
    task: tomexam
