apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluence
  namespace: default
  labels:
    app: confluence
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confluence
  template:
    metadata:
      labels:
        app: confluence
        version: v1
    spec:
      containers:
      - name: confluence
        image: slzcc/confluence:7.10.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8090
        - name: interaction
          containerPort: 8000
        - name: synchrony
          containerPort: 8091
        volumeMounts:
        - mountPath: "/var/atlassian/application-data/confluence"
          name: data
        - mountPath: "/opt/atlassian/confluence/conf/server.xml"
          name: config
          subPath: server.xml
        - mountPath: "/opt/atlassian/confluence/conf/setenv.sh"
          name: config
          subPath: setenv.sh
        - mountPath: /usr/share/zoneinfo
          name: usr-local-timezone
          readOnly: true
        env:
        - name: TZ
          value: "Asia/Shanghai"
      volumes:
      - name: usr-local-timezone
        hostPath:
          path: /usr/share/zoneinfo
          type: DirectoryOrCreate
      - hostPath:
          path: "/var/data/opt/atlassian/confluence/data"
        name: data
      - name: config
        configMap:
          name: "confluence-server"
          items:
            - key: server.xml
              path: server.xml
            - key: setenv.sh
              path: setenv.sh
