apiVersion: v1
kind: Service
metadata:
  name: example-nginx
  namespace: default
spec:
  ports:
   - name: http
     port: 80
     targetPort: 80
     protocol: TCP
  selector:
    app: example-nginx
