#apiVersion: extensions/v1beta1
#kind: Deployment
apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-logging-v1
#  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: elasticsearch-logging
    version: v1
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      nodeSelector:
        role: gcloud
      containers:
      - image: registry.aliyuncs.com/slzcc/elasticsearch:5.5
        name: elasticsearch
#        resources:
#          limits:
#            cpu: 1000m
#          requests:
#            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-persistent-storage
          mountPath: "/usr/share/elasticsearch/data"
        - name: es-plugins
          mountPath: "/usr/share/elasticsearch/plugins"
      volumes:
      - name: es-persistent-storage
        hostPath:
          path: "/data/elasticsearch"
      - name: es-plugins
        hostPath:
          path: "/data/elasticsearch-plugins"
