apiVersion: v1
kind: ReplicationController
metadata:
  name: logstash
#  namespace: kube-system
  labels:
    k8s-app: logstash
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: logstash
    version: v1
  template:
    metadata:
      labels:
        k8s-app: logstash
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      nodeSelector:
        role: elk
      containers:
      - image: registry.aliyuncs.com/slzcc/logstash-build
        name: logstash
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 514
          name: input
          protocol: TCP
        - containerPort: 514
          name: output
          protocol: UDP
        command:
        - '/logstash-5.1.1/bin/logstash'
        - '-f'
        - '/etc/logstash/logstash.conf'
        - '-w 20'
        volumeMounts:
          - mountPath: "/etc/logstash/"
            name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: logstash
