apiVersion: v1
kind: Service
metadata:
  name: logstash
#  namespace: kube-system
  labels:
    k8s-app: logstash
#    kubernetes.io/cluster-service: "true"
#    kubernetes.io/name: "logstash"
spec:
  ports:
  - port: 514
    name: input
    protocol: TCP
    targetPort: input
  - port: 514
    name: output
    protocol: UDP
    targetPort: output
  selector:
    k8s-app: logstash
  clusterIP: None
