apiVersion: v1
kind: Service
metadata:
  name: bamboo
  namespace: default
spec:
#  clusterIP: None
#  type: LoadBalancer
#  type: NodePort
  ports:
   - name: http
     port: 8085
     targetPort: 8085
     protocol: TCP
#     nodePort: 8085
  selector:
    app: cheese
    task: bamboo
