apiVersion: extensions/v1beta1
kind: Deployment
metadata:
#  namespace: kube-system
  name: nginxplus
  namespace: default
  labels:
    app: cheese
    cheese: nginxplus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: nginxplus
  template:
    metadata:
      labels:
        app: cheese
        task: nginxplus
        version: v0.0.1
    spec:
      nodeSelector:
        role: shileizcc.com
      containers:
      - name: nginxplus
        image: slzcc/nginxplus:1.15.7.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
          - mountPath: "/etc/nginx/conf.d/"
            name: index
        env:
        - name: TZ
          value: "Asia/Shanghai"
      imagePullSecrets:
        - name: myregistrykey
      volumes:
        - name: index
          configMap:
            name: nginxplus-index
            items:
              - key: index.conf
                path: index.conf
              - key: status_password
                path: status_password
              - key: secret_password
                path: secret_password
