apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxplus-index
  namespace: default
data:
  www.shileizcc.com.conf: |
    upstream server_zendesk {
        server 104.16.51.111 weight=1 max_fails=3 fail_timeout=8s;
        server 104.16.53.111 weight=1 max_fails=3 fail_timeout=8s;
    }
    server {
        listen 80;
        server_name www.shileizcc.com;

        location / {
            proxy_next_upstream http_502 http_504 error timeout invalid_header;
            proxy_pass http://server_zendesk;
            proxy_set_header Host billance.zendesk.com;
            proxy_set_header X-Forwarded-For $remote_addr;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }

  acme_registry.conf: |-
    ## Registry TLS
    server {
        
        listen 80;
        location ^~ /.well-known/acme-challenge/ {
            alias /mnt/www/challenges/;
            try_files $uri =404;
        }
        location / {
            rewrite ^/(.*)$ https://wiki.shileizcc.com/$1 permanent;
        }
    }
        
  wiki.conf: |-
    upstream wiki {
        zone upstrean-wiki 64k;
        server  confluence.default.svc.cluster.local service=_http._tcp resolve;
    }
    upstream wiki_synchrony {
        zone upstrean-wiki-synchrony 64k;
        server  confluence.default.svc.cluster.local service=_synchrony._tcp resolve;
    }

    ## wiki
    server  {
        
        listen 80;
        status_zone wiki;
        server_name wiki.shileizcc.com;

        location  / {
            
            return 301 /confluence;

            #  禁止非GET|HEAD|POST方式的抓取
            if ($request_method !~ ^(GET|HEAD|POST)$) {
            return 403;
            }
            if ($http_user_agent ~* (Scrapy|HttpClient)) {
            return 403;
            }
        }
        location /confluence {
            proxy_http_version 1.1;
            client_max_body_size 100m;
            proxy_set_header Host confluence.default.svc.cluster.local;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Connection "";
            proxy_pass http://wiki/confluence;
            proxy_connect_timeout 1800;
            proxy_send_timeout 1800;
            proxy_read_timeout 1800;
            proxy_buffering on;
            proxy_buffers 4 256k;
            proxy_buffer_size 256k;
            proxy_temp_path /tmp/proxy_temp 1 2;
            proxy_max_temp_file_size 2048m;
            proxy_temp_file_write_size 256k;
        }
        location /synchrony {
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host confluence.default.svc.cluster.local;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://wiki_synchrony/synchrony;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
        location ^~ /.well-known/acme-challenge/ {
            alias /mnt/www/challenges/;
            try_files $uri =404;
        }
        location /confluence/rest/analytics/1.0/publish/bulk {
            deny all;
            return 200;
       }
    }

  mirror.conf: |-
    upstream mirror {
        zone upstrean-mirror 64k;
        server mirror.default.svc.cluster.local service=_http._tcp resolve;
    }

    ## mirror
    server  {
        
        listen 80;
        status_zone mirror;
        server_name mirror.shileizcc.com;

        location  / {
            proxy_http_version 1.1;
            proxy_pass  http://mirror;
            proxy_redirect off;
            proxy_set_header Connection "";
            proxy_set_header Host mirror.default.svc.cluster.local;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 50m;
            client_body_buffer_size 256k;
            proxy_connect_timeout 30;
            proxy_send_timeout 30;
            proxy_read_timeout 60;
            proxy_buffer_size 256k;
            proxy_buffers 4 256k;
            proxy_busy_buffers_size 256k;
            proxy_temp_file_write_size 256k;
            proxy_next_upstream error timeout invalid_header http_500 http_503 http_404;
            proxy_max_temp_file_size 128m;
            error_page  404 /var/data/logo/T/404.jpg;
            error_page  502 /var/data/logo/T/502.png;
        }
        location ^~ /.well-known/acme-challenge/ {
            alias /mnt/www/challenges/;
            try_files $uri =404;
        }
    }

  status.conf: |-
    ## status
    server {
        listen 80;
        status_zone status;
        server_name status.shileizcc.com;
        
        location ^~ /.well-known/acme-challenge/ {
            alias /mnt/www/challenges/;
            try_files $uri =404;
        }
        location / {
            return 301 /dashboard.html;
        }
        location /api {
            api write=on;
            limit_except GET {
                auth_basic "NGINX Plus API";
                auth_basic_user_file status_password;
            }
            # directives limiting access to the API
        }
        location = /dashboard.html {
            root   /usr/share/nginx/html;
        }
        # Redirect requests made to the old dashboard
        location = /status.html {
            return 301 /dashboard.html;
        }
        location /swagger-ui {
            root   /usr/share/nginx/html;
        }
        
    }

  status_password:
    Slzcc:$apr1$O4Z4uO/z$015EVKlnoe3ZJLaKCedZD1

  secret_password:
    Slzcc:$apr1$ZldTwd1G$WBUmBMoFiOYCjGdZmdg.q.
