apiVersion: extensions/v1beta1
kind: Deployment
metadata:
#  namespace: kube-system
  name: nginxplus
  namespace: default
  labels:
    app: cheese
    cheese: nginxplus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: nginxplus
  template:
    metadata:
      labels:
        app: cheese
        task: nginxplus
        version: v0.0.1
    spec:
      nodeSelector:
        role: shileizcc.com
      containers:
      - name: nginxplus
        image: registry.aliyuncs.com/slzcc/nginxplus
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
          - mountPath: "/mirror"
            name: mirror
#          - mountPath: "/etc/nginx/nginx"
#            name: nginxplus-nginx
#          - mountPath: "/etc/nginx/conf.d"
#            name: nginxplus-password-web
          - mountPath: "/etc/nginx"
            name: nginx
#          - mountPath: "/etc/nginx/conf.d"
#            name: nginxplus-wiki
#          - mountPath: "/etc/nginx/conf.d"
#            name: nginxplus-gateway
#          - mountPath: "/etc/nginx/conf.d"
#            name: nginxplus-mirror-data
#          - mountPath: "/etc/nginx/conf.d"
#            name: nginxplus-mirror
#          - mountPath: "/etc/nginx/conf.d"
#            name: nginxplus-status
#          - mountPath: "/etc/nginx/conf.d"
#            name: nginxplus-k8s
        env:
        - name: TZ
          value: "Asia/Shanghai"
      imagePullSecrets:
        - name: myregistrykey
      volumes:
        - hostPath:
            path: "/var/data/work_dir/mirror"
          name: mirror 
#        - name: nginxplus-password-web
#          configMap:
#            name: nginxplus-password-web
#        - name: nginxplus-nginx
#          configMap:
#            name: nginxplus-nginx
#        - name: nginxplus-wiki
#          configMap:
#            name: nginxplus-wiki
#        - name: nginxplus-gateway
#          configMap:
#            name: nginxplus-gateway
#        - name: nginxplus-k8s
#          configMap:
#            name: nginxplus-k8s
#        - name: nginxplus-mirror-data
#          configMap:
#            name: nginxplus-mirror-data
#        - name: nginxplus-mirror
#          configMap:
#            name: nginxplus-mirror
#        - name: nginxplus-status
#          configMap:
#            name: nginxplus-status
        - hostPath:
            path: "/var/data/opt/nginxplus/"
          name: nginx
