apiVersion: v1
kind: Service
metadata:
  name: nginxplus
  namespace: default
spec:
  ports:
   - name: http
     port: 80
     targetPort: 80
     protocol: TCP
   - name: https
     port: 443
     protocol: TCP 
#   - name: status
#     port: 8081
#     protocol: TCP
  selector:
    app: cheese
    task: nginxplus
