apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxplus-nginx
  namespace: default
data:
  nginx.conf: |-
        user  nginx;
        worker_processes  auto;

        error_log  /var/log/nginx/error.log notice;
        pid        /var/run/nginx.pid;


        events {
            worker_connections  10240;
        }


        http {
            include       /etc/nginx/mime.types;
            default_type  application/octet-stream;
            limit_req_zone $binary_remote_addr zone=allips:10m rate=20r/s;
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Credentials true;
            add_header Access-Control-Allow-Headers *;
            add_header Access-Control-Allow-Methods GET,POST,OPTIONS;

        #    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
        #                      '$status $body_bytes_sent "$http_referer" '
        #                      '"$http_user_agent" "$http_x_forwarded_for"';
        #    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent"$http_referer" "$http_user_agent" [unknown_content];'

            log_format main '$proxy_add_x_forwarded_for | $time_local | $request | $status | $body_bytes_sent | '
                            '$request_body | $content_length | $http_referer | $http_user_agent | '
                            '$http_cookie | $remote_addr | $hostname | $upstream_addr | $upstream_response_time | $request_time';

        #    log_format main '$proxy_add_x_forwarded_for | $time_local | $request | $status | $body_bytes_sent | '
        #                    '"$request_body" | $content_length | "$http_referer" | "$http_user_agent" | '
        #                    '"$http_cookie" | $remote_addr | $hostname | $upstream_addr | $upstream_response_time | $request_time';

        #    log_format main '$proxy_add_x_forwarded_for | $time_local | "$request" | $status | $body_bytes_sent | '
        #                    '$content_length | "$http_referer" | "$http_user_agent" | '
        #                    '"$http_cookie" | $remote_addr | $hostname | $upstream_addr | $upstream_response_time | $request_time';

            access_log  /var/log/nginx/access.log  main;

            sendfile        on;
            #tcp_nopush     on;
            client_body_buffer_size 102400;
            keepalive_timeout  600;
            ignore_invalid_headers off;
            underscores_in_headers on;

            #gzip  on;

            include /etc/nginx/conf.d/*.conf;
            limit_req_zone $binary_remote_addr zone=shileizcc_com:10m rate=5r/s;
        }


        # TCP/UDP proxy and load balancing block
        #
        #stream {
            # Example configuration for TCP load balancing

            #upstream stream_backend {
            #    zone tcp_servers 64k;
            #    server backend1.example.com:12345;
            #    server backend2.example.com:12345;
            #}

            #server {
            #    listen 12345;
            #    status_zone tcp_server;
            #    proxy_pass stream_backend;
            #}
        #}
        #stream {
            # Example configuration for TCP load balancing

        #    upstream stream_backend {
        #        zone tcp_servers 64k;
        #        server 10.44.0.0:8085;
        #    }

        #    server {
        #        listen 80;
        #        status_zone tcp_server;
        #        server_name shileizcc.com;
        #        proxy_pass stream_backend;
        #    }
        #}
