apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxplus
  namespace: default
  labels:
    app: nginxplus
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxplus
  template:
    metadata:
      labels:
        app: nginxplus
        version: v1
    spec:
      containers:
      - name: nginxplus
        image: slzcc/nginxplus:1.19.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        env:
        - name: TZ
          value: "Asia/Shanghai"
        volumeMounts:
          - mountPath: "/etc/nginx/conf.d/"
            name: index
          - mountPath: "/etc/nginx/nginx.conf"
            name: nginx
            subPath: nginx.conf
          - mountPath: "/mnt/www/challenges/"
            name: data
          - mountPath: /usr/share/zoneinfo
            name: usr-local-timezone
            readOnly: true
      volumes:
        - name: usr-local-timezone
          hostPath:
            path: /usr/share/zoneinfo
            type: DirectoryOrCreate
        - hostPath:
            path: "/mnt/www/challenges/"
          name: data
        - name: index
          configMap:
            name: nginxplus-index
        - name: nginx
          configMap:
            name: nginxplus-nginx
            items:
              - key: nginx.conf
                path: nginx.conf
