apiVersion: v1
kind: Service
metadata:
  name: nginxplus
  namespace: default
  labels:
    app: nginxplus
    service: nginxplus
spec:
  ports:
   - name: http
     port: 80
     targetPort: 80
     protocol: TCP
  selector:
    app: nginxplus
