apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxplus-nginx
  namespace: default
data:
  nginx.conf: |-
    user www-data;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  10240;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        limit_req_zone $binary_remote_addr zone=allips:10m rate=20r/s;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Credentials true;
        add_header Access-Control-Allow-Headers *;
        add_header Access-Control-Allow-Methods GET,POST,OPTIONS;

        log_format main  escape=json '{ "@timestamp": "$time_local", '
                             '"remote_addr": "$remote_addr", '
                             '"upstream_addr": "$upstream_addr",'
                             '"remote_user": "$remote_user", '
                             '"body_bytes_sent": "$body_bytes_sent", '
                             '"request_time": "$request_time", '
                             '"status": "$status", '
                             '"request": "$request", '
                             '"request_method": "$request_method", '
                             '"http_referrer": "$http_referer", '
                             '"body_bytes_sent":"$body_bytes_sent", '
                             '"http_x_forwarded_for": "$http_x_forwarded_for", '
                             '"host":""$host",'
                             '"remote_addr":""$remote_addr",'
                             '"http_user_agent": "$http_user_agent",'
                             '"http_uri": "$uri",'
                             '"http_host":"$http_host" }';


        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;
        client_body_buffer_size 102400;
        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
        limit_req_zone $binary_remote_addr zone=shileizcc_com:10m rate=5r/s;
    }


    # TCP/UDP proxy and load balancing block
    #
    #stream {
        # Example configuration for TCP load balancing

        #upstream stream_backend {
        #    zone tcp_servers 64k;
        #    server backend1.example.com:12345;
        #    server backend2.example.com:12345;
        #}

        #server {
        #    listen 12345;
        #    status_zone tcp_server;
        #    proxy_pass stream_backend;
        #}
    #}
