apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-watermark
  namespace: default
  labels:
    app: cheese
    cheese: nginx-watermark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: nginx-watermark
  template:
    metadata:
      labels:
        app: cheese
        task: nginx-watermark
        version: v0.0.1
    spec:
      nodeSelector:
        role: shileizcc.com
      containers:
      - name: nginx-mirror
	imagePullPolicy: Always
        image: registry.aliyuncs.com/slzcc/nginx:watermark
        ports:
        - name: http
          containerPort: 80
