apiVersion: v1
kind: Service
metadata:
  name: robot
  namespace: default
  labels:
    app: robot
    service: robot
spec:
  ports:
   - name: http
     port: 80
     targetPort: 80
     protocol: TCP
  selector:
    app: robot
