apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: st
  namespace: default
  labels:
    app: cheese
    task: st
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: st
  template:
    metadata:
      labels:
        app: cheese
        task: st
        version: v0.0.1
    spec:
      containers:
      - name: st
        image: slzcc/ansible:demo4
        command:
          - sleep
          - "3600000"
      restartPolicy: Always
