apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "nginx"
spec:
#  type: NodePort
  clusterIP: None
  selector:
    app: nginx
  ports:
   - name: http
     port: 80
     targetPort: 80
#     nodePort: 801
     protocol: TCP
#   - name: https
#     port: 443
#     targetPort: 443
#     nodePort: 4431
#     protocol: TCP 
#   - name: status
#     port: 8081
#     targetPort: 443
#     nodePort: 4431
#     protocol: TCP
