apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  selector:
    app: cheese
    task: alertmanager
#  type: NodePort
  clusterIP: None
  ports:
  - name: http
    protocol: TCP
    port: 9093
#    nodePort: 30800
#    clusterIP: 10.111.193.110
#  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager
  labels:
    app: cheese
    task: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: alertmanager
  template:
    metadata:
      labels:
        app: cheese
        task: alertmanager
        version: v0.0.1
    spec:
      nodeSelector:
        role: mesos3
#      hostNetwork: true
      containers:
      - name: alertmanager
        image: prom/alertmanager
        ports:
        - name: http
          containerPort: 9093
          hostPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager
