apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: cheese
    task: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: prometheus
  template:
    metadata:
      labels:
        app: cheese
        task: prometheus
        version: v0.0.1
    spec:
      nodeSelector:
        role: mesos3
#      hostNetwork: true
      containers:
      - name: prometheus
        image: quay.io/coreos/prometheus:0.19.2
#        image: registry.aliyuncs.com/slzcc/prometheus
        args:
          - '-storage.local.retention=6h'
          - '-storage.local.memory-chunks=500000'
          - '-config.file=/etc/prometheus/prometheus.yml'
         # - '-alertmanager.url=http://101.200.39.80:30800'
          - '-alertmanager.url=http://alertmanager:9093'
        ports:
        - name: web
          containerPort: 9090
#          hostPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: alert-config-volume
          mountPath: /etc/prometheus/rules
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
      - name: alert-config-volume
        configMap:
          name: alert.rules
