apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: cheese
    task: prometheus
  type: ClusterIP
#  clusterIP: None
#  type: LoadBalancer
#  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 9090
#    nodePort: 30900
