---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
        version: v1.0.0
    spec:
      nodeSelector:
        role: shileizcc.com
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      serviceAccountName: traefik-ingress-controller
      containers:
      - image: traefik
        imagePullPolicy: IfNotPresent
        name: traefik-ingress-lb
        resources:
          limits:
            cpu: 200m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: web
          containerPort: 8088
#          hostPort: 8088
        - name: https
          containerPort: 443
          hostPort: 443
        args:
        - --etcd
        - --etcd.endpoint=127.0.0.1:2379
        - --kubernetes
       # - --kubernetes
       # - --kubernetes.endpoint=127.0.0.1:8080
       # - --etcd.endpoint=101.200.83.130:4001
