---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
        version: v1.0.0
    spec:
      nodeSelector:
        role: shileizcc.com
      terminationGracePeriodSeconds: 60
      serviceAccountName: traefik-ingress-controller
      containers:
      - image: traefik:1.1.2
        imagePullPolicy: IfNotPresent
        name: traefik-ingress-lb
        resources:
          limits:
            cpu: 200m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: web
          containerPort: 8088
        - name: https
          containerPort: 443
          hostPort: 443
        args:
        - --acme
#        - --acme.storage = "traefik/acme/account"
#        - --acme.storageFile = "acme.json"
#        - --acme.onDemand = true
#        - --acme.entryPoint = "https"
#        - --acme.OnHostRule = true
        - --etcd
        - --etcd.endpoint=172.17.48.104:2379
        - --etcd.watch=true
#        - --api
        - --kubernetes
        - --logLevel=INFO
        - --etcd.tls
        - --etcd.tls.ca=/etc/kubernetes/pki/etcd/etcd-ca.pem
        - --etcd.tls.cert=/etc/kubernetes/pki/etcd/etcd.pem
        - --etcd.tls.key=/etc/kubernetes/pki/etcd/etcd-key.pem
        volumeMounts:
        - mountPath: /etc/kubernetes/pki/etcd/
          name: etcd-certs
      volumes:
      - hostPath:
          path: /etc/kubernetes/pki/etcd/
          type: DirectoryOrCreate
        name: etcd-certs
