---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
        version: v1.0.0
    spec:
      nodeSelector:
        role: shileizcc.com
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      serviceAccountName: traefik-ingress-controller
      containers:
      - image: traefik
        imagePullPolicy: IfNotPresent
        name: traefik-ingress-lb
        resources:
          limits:
            cpu: 200m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: web
          containerPort: 8088
        - name: https
          containerPort: 443
          hostPort: 443
        args:
        - --etcd
        - --etcd.endpoint=127.0.0.1:2379
        - --api
        - --kubernetes
        - --logLevel=INFO
        - --etcd.tls
        - --etcd.tls.ca=/etc/kubernetes/pki/etcd/ca.crt
        - --etcd.tls.cert=/etc/kubernetes/pki/etcd/server.crt
        - --etcd.tls.key=/etc/kubernetes/pki/etcd/server.key
        volumeMounts:
        - mountPath: /etc/kubernetes/pki/etcd
          name: etcd-certs
        - mountPath: /cert
          name: ssl-certs
      volumes:
      - hostPath:
          path: /etc/kubernetes/pki/etcd
          type: DirectoryOrCreate
        name: etcd-certs
      - hostPath:
          path: /mnt
        name: ssl-certs
