apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  # In a production setup, we recommend accessing Grafana through an external Loadbalancer
  # or through a public IP.
  # type: LoadBalancer
#  type: NodePort
#  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 3000
    targetPort: 3000
#    nodePort: 30300
  selector:
    app: cheese
    task: grafana
