kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kodexplorer-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: kodexplorer-datas
