apiVersion: v1
kind: PersistentVolume
metadata:
  name: kodexplorer-datas
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: kodexplorer-datas
  nfs:
    # FIXME: use the right IP
    server: 192.168.53.38
    path: "/exports/kodexplorer/data"
