apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: confluence-data-backup
spec:
  schedule: "59 23 * * 2-6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: confluence-data-backup
            image: busybox
            args:
            - /bin/sh
            - -c
            - tar zcf /dataBackup/confluence_`date +%F_%R`.tar.gz -C /data data
            volumeMounts:
              - mountPath: "/data"
                name: data
              - mountPath: "/dataBackup"
                name: backup
            env:
            - name: TZ
              value: "Asia/Shanghai"
          volumes:
            - hostPath:
                path: "/var/data/opt/altassian/confluence"
              name: data
            - hostPath:
                path: "/var/data/confluenceBackup"
              name: backup
          restartPolicy: OnFailure
