apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - tar zcf confluence_`data +%F_%R`.tar.gz -C /mysqlBackup data
            volumeMounts:
              - mountPath: "/mysqlBackup"
                name: data
            env:
            - name: TZ
              value: "Asia/Shanghai"
          volumes:
            - hostPath:
                path: "/var/data/opt/altassian/confluence"
              name: data
          restartPolicy: OnFailure
