apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysqldump
spec:
  schedule: "59 23 * * 2-6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysqldump
            image: registry.aliyuncs.com/slzcc/mysql:5.6
            args:
            - /bin/sh
            - -c
            - mysqldump -uroot -pChengcheng_slzcc -h mysql confluence > /mysqlBackup/confluence_`date +%F_%R`.sql
            volumeMounts:
              - mountPath: "/mysqlBackup"
                name: data
            env:
            - name: TZ
              value: "Asia/Shanghai"
          volumes:
            - hostPath:
                path: "/var/data/mysqlBackup"
              name: data
          restartPolicy: OnFailure
