apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysqldump
spec:
  schedule: "* */23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysqldump
            image: registry.aliyuncs.com/slzcc/mysql:5.6
            args:
            - /bin/sh
            - -c
            - mysqldump -uroot -pChengcheng_slzcc -h mysql.default.svc confluence > confluence_date +%F_%R.sql
          restartPolicy: OnFailure
