apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginxplus-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "shileizcc.com"
    - "*.shileizcc.com"
    # tls:
    #   httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "shileizcc.com"
    - "*.shileizcc.com"
    tls:
      mode: SIMPLE
      credentialName: shileizcc-tls

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginxplus-virtualservice
spec:
  hosts:
  - shileizcc.com
  - wiki.shileizcc.com
  - status.shileizcc.com
  - www.shileizcc.com
  - mirror.shileizcc.com
  - "*.shileizcc.com"
  gateways:
  - istio-system/nginxplus-gateway
  http:
  - route:
    - destination:
        host: nginxplus.default.svc.cluster.local
        subset: v1
    headers:
        request:
          remove:
            - x-b3-sampled
          add: 
            x-b3-sampled: '0'
            
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginxplus-destinationrule
spec:
  host: nginxplus.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1

# set ingressgateway externalTrafficPolicy: Local 