apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockercfg: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5hbGl5dW5jcy5jb20iOiB7CgkJCSJhdXRoIjogImVtaGxibmhwYm1GcGJta3pPRUIyYVhBdWNYRXVZMjl0T21FMU1UazJNalkwIgoJCX0KCX0KfQ==
type: kubernetes.io/dockercfg
