kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dzzoffice-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: dzzoffice-datas
