apiVersion: v1
kind: PersistentVolume
metadata:
  name: dzzoffice-datas
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: dzzoffice-datas
  nfs:
    # FIXME: use the right IP
    server: 192.168.53.38
    path: "/exports/dzzoffice/data"
