apiVersion: extensions/v1beta1
kind: Deployment
metadata:
#  namespace: kube-system
  name: mirror-data
  namespace: default
  labels:
    app: cheese
    cheese: mirror-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: mirror-data
  template:
    metadata:
      labels:
        app: cheese
        task: mirror-data
        version: v0.0.1
    spec:
      nodeSelector:
        role: shileizcc.com
      containers:
      - name: mirror-data
        workingDir: /mirror
        image: registry.aliyuncs.com/slzcc/java-web:mirror
        imagePullPolicy: IfNotPresent
        command: [ 
               "/usr/bin/java", 
               "-jar", 
               "/usr/src/app/app.jar", 
               "8080" 
               ]
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
          - mountPath: "/mirror"
            name: mirror-data
        env:
        - name: TZ
          value: "Asia/Shanghai"
      imagePullSecrets:
        - name: myregistrykey
      volumes:
        - hostPath:
            path: "/var/data/work_dir/mirror"
          name: mirror-data
