apiVersion: v1
kind: Service
metadata:
  name: mirror-data
  namespace: default
spec:
  ports:
   - name: http
     port: 8080
     targetPort: 8080
     protocol: TCP
  selector:
    app: cheese
    task: mirror-data
