apiVersion: v1
kind: PersistentVolume
metadata:
  name: owncloud-data
spec:
  capacity:
    storage: 70Gi
  accessModes:
    - ReadWriteMany
  storageClassName: owncloud-data
  nfs:
    # FIXME: use the right IP
    server: 10.40.0.6
    path: "/exports/owncloud/data"
