apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  namespace: default
  labels:
    app: cheese
    cheese: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: gateway
  template:
    metadata:
      labels:
        app: cheese
        task: gateway
        version: v0.0.1
    spec:
      nodeSelector:
        role: shileizcc.com
      containers:
      - name: gateway
        image: registry.aliyuncs.com/slzcc/nginx:gateway
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
          - mountPath: "/etc/nginx/conf.d"
            name: config-volume
      imagePullSecrets:
        - name: myregistrykey
      volumes:
        - name: config-volume
          configMap:
            name: gateway
