apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  capacity:
    storage: 70Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nextcloud-data
  nfs:
    # FIXME: use the right IP
    server: 10.40.0.6
    path: "/exports/nextcloud/data"
