apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxplus-status
  namespace: default
data:
  status.conf: |-
        server {
                listen 80;
                server_name status.shileizcc.com;
                root /usr/share/nginx/html;
                # Redirect requests for / to /status.html
                location = / {
                    return 301 /status.html;
                }
                location = /status.html { }
                # Everything beginning with /status (except for /status.html) is
                # processed by the status handler
                location /status {
                    status;
        #            auth_basic                  "Please Input username/password";
        #            auth_basic_user_file        status-password;
                }
        }

        server {
               listen 80;
               location ^~ /.well-known/acme-challenge/ {
                   alias /var/data/challenges/;
                   try_files $uri =404;
               }
               location / {
                   rewrite ^/(.*)$ https://shileizcc.com/$1 permanent;
               }
        }
