apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ssl
  labels:
    app: cheese
    cheese: nginx-ssl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: nginx-ssl
  template:
    metadata:
      labels:
        app: cheese
        task: nginx-ssl
        version: v0.0.1
    spec:
      nodeSelector:
        role: shileizcc.com
      hostNetwork: true
      containers:
      - name: nginx
        image: registry.aliyuncs.com/slzcc/nginx-1.11.5
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        volumeMounts:
          - mountPath: "/etc/nginx"
            name: data
      imagePullSecrets:
        - name: myregistrykey
      volumes:
        - hostPath:
            path: "/etc/nginx"
          name: data
