apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
   - name: http
     port: 80
     targetPort: 80
     protocol: TCP
     nodePort: 80
  selector:
    app: cheese
    task: nginx
  type: NodePort
