apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
   - name: http
     port: 8080
#     targetPort: 8080
#     nodePort: 30800
     protocol: TCP
   - name: jnip
     port: 50000
     targetPort: 50000
     protocol: TCP
  selector:
    app: cheese
    task: jenkins
