apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: cheese
    cheese: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: jenkins
  template:
    metadata:
      labels:
        app: cheese
        task: jenkins
        version: v0.0.1
    spec:
      nodeSelector:
        role: xsj
      containers:
      - name: jenkins
        image: registry.aliyuncs.com/slzcc/jenkins:2.79
        ports:
        - name: http
          containerPort: 8080
        - name: jnlp
          containerPort: 50000
        env:
        - name: TZ
          value: "Asia/Shanghai"
        volumeMounts:
          - mountPath: "/var/jenkins_home"
            name: home
      volumes:
        - hostPath:
            path: "/var/jenkins_home"
          name: home
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
#  type: NodePort
#  clusterIP: None
  ports:
   - name: http
     port: 8080
     targetPort: 8080
#     nodePort: 30800
     protocol: TCP
   - name: jnlp
     port: 50000
     targetPort: 50000
     protocol: TCP
  selector:
    app: cheese
    task: jenkins

