apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: desktop
  namespace: default
  labels:
    app: cheese
    task: desktop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: desktop
  template:
    metadata:
      labels:
        app: cheese
        task: desktop
        version: v0.0.1
    spec:
      nodeSelector:
        role: shileizcc.com
      containers:
      - name: desktop
#        image: registry.aliyuncs.com/slzcc/ubuntu-desktop-lxde-vnc:password
        image: dorowu/ubuntu-desktop-lxde-vnc:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: vnc
          containerPort: 5900
        - name: http
          containerPort: 80
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: VNC_PASSWORD
          value: "shileizcc.com"
      imagePullSecrets:
        - name: myregistrykey
