apiVersion: v1
kind: Service
metadata:
  name: desktop
  namespace: default
spec:
  ports:
   - name: vnc
     port: 5900
     targetPort: 5900
     protocol: TCP
     nodePort: 59000
  type: NodePort
  selector:
    app: cheese
    task: desktop
