apiVersion: v1
kind: Service
metadata:
  name: desktop
  namespace: default
spec:
  ports:
   - name: vnc
     port: 5900
     targetPort: 5900
     protocol: TCP
     nodePort: 31000
   - name: http
     port: 80
     targetPort: 6080
     protocol: TCP
  type: NodePort
  selector:
    app: cheese
    task: desktop
