apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: confluence-virtualservice
spec:
  hosts:
  - "confluence"
  http:
  - route:
    - destination:
        host: confluence
        port:
          number: 8090
        subset: v1
      headers:
        request:
          remove:
            - x-b3-sampled
          add: 
            x-b3-sampled: '0'

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: confluence-destinationrule
spec:
  host: confluence
  subsets:
  - name: v1
    labels:
      version: v1

# https://jira.atlassian.com/browse/CONFSERVER-59477