apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: confluence-virtualservice
spec:
  hosts:
  - "wiki.shileizcc.com"
  http:
  - route:
    - destination:
        host: confluence
        port:
          number: 8090
        subset: v1

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: confluence-destinationrule
spec:
  host: confluence
  subsets:
  - name: v1
    labels:
      version: v1