apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: confluence-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: confluence-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - default/confluence-gateway
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: confluence
        port:
          number: 8090
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: confluence-destinationrule
spec:
  host: confluence
  subsets:
  - name: v1
    labels:
      version: v1
