#apiVersion: extensions/v1beta1
apiVersion: networking.k8s.io/v1beta1
#apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cheese
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/permanent-redirect-code: "301"
spec:
  rules:
  - host: www.shileizcc.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginxplus
          servicePort: http
  - host: shileizcc.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginxplus
          servicePort: http
  - host: wiki.shileizcc.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginxplus
          servicePort: http
  - host: mirror.shileizcc.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginxplus
          servicePort: http
  - host: status.shileizcc.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginxplus
          servicePort: http
  tls:
  - hosts:
    - shileizcc.com
    - www.shileizcc.com
    - wiki.shileizcc.com
    - status.shileizcc.com
    - mirror.shileizcc.com
    secretName: shileizcc-ingress
