apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxplus-all
  namespace: default
data:
    index.conf: |-
    resolver 10.96.0.10 valid=1s;

    upstream wiki {
    zone upstrean-wiki 64k;
    server  confluence.default.svc.cluster.local service=_http._tcp resolve;
    }

    upstream k8s {
    zone upstrean-k8s 64k;
    server  dashboard.kube-system.svc.cluster.local service=_http._tcp resolve;
    }

    upstream gateway {
    zone upstrean-gateway 64k;
    server  gateway.default.svc.cluster.local service=_http._tcp resolve;
    }

    upstream jenkins {
    zone upstrean-data 64k;
    server  jenkins.default.svc.cluster.local service=_http._tcp resolve;
    }

    upstream mirror {
    zone upstrean-mirror 64k;
    server  mirror.default.svc.cluster.local service=_http._tcp resolve;
    }

    ## jenkins
    server  {
                    listen 80;
                    status_zone jenkins;
                    server_name dev.shileizcc.com;
            location  / {
                    proxy_pass  http://jenkins;
                    proxy_redirect off;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header REMOTE-HOST $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    client_max_body_size 50m;
                    client_body_buffer_size 256k;
                    proxy_connect_timeout 30;
                    proxy_send_timeout 30;
                    proxy_read_timeout 60;
                    proxy_buffer_size 256k;
                    proxy_buffers 4 256k;
                    proxy_busy_buffers_size 256k;
                    proxy_temp_file_write_size 256k;
                    proxy_next_upstream error timeout invalid_header http_500 http_503 http_404;
                    proxy_max_temp_file_size 128m;
                    error_page  404 /var/data/logo/T/404.jpg;
                    error_page  502 /var/data/logo/T/502.png;
            }

            location ~* ^(/viewpage.action|pages/viewpage.action) {
                    return 403;
            }
            location ^~ /.git {
                    return 403;
            }
            location ~*.php {
                    return 403;
            }
    }

    ## gateway
    server  {
                    listen 80;
                    status_zone gateway;
                    server_name www.shileizcc.com;
                    location  / {
                    proxy_pass  http://gateway;
                    proxy_redirect off;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header REMOTE-HOST $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    client_max_body_size 50m;
                    client_body_buffer_size 256k;
                    proxy_connect_timeout 30;
                    proxy_send_timeout 30;
                    proxy_read_timeout 60;
                    proxy_buffer_size 256k;
                    proxy_buffers 4 256k;
                    proxy_busy_buffers_size 256k;
                    proxy_temp_file_write_size 256k;
                    proxy_max_temp_file_size 128m;
                    error_page  404 /var/data/logo/T/404.jpg;
                    error_page  502 /var/data/logo/T/502.png;
            }
            location ~* ^(/viewpage.action|pages/viewpage.action) {
                    return 403;
            }
            location ^~ /.git {
                    return 403;
            }
            location ~*.php {
                    return 403;
            }
    }

    ## wiki
    server  {
                    listen 80;
                    status_zone wiki;
                    server_name wiki.shileizcc.com shileizcc.com;
                    location  / {
                    proxy_pass  http://wiki;
                    proxy_redirect off;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header REMOTE-HOST $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    client_max_body_size 50m;
                    client_body_buffer_size 256k;
                    proxy_connect_timeout 30;
                    proxy_send_timeout 30;
                    proxy_read_timeout 60;
                    proxy_buffer_size 256k;
                    proxy_buffers 4 256k;
                    proxy_busy_buffers_size 256k;
                    proxy_temp_file_write_size 256k;
                    proxy_max_temp_file_size 128m;
                    error_page  404 /var/data/logo/T/404.jpg;
                    error_page  502 /var/data/logo/T/502.png;
            }
            location ~* ^(/viewpage.action|pages/viewpage.action) {
                    return 403;
            }
            location ^~ /.git {
                    return 403;
            }
            location ~*.php {
                    return 403;
            }
    }


    ## k8s
    server  {
                    listen 80;
            status_zone k8s;
                    server_name k8s.shileizcc.com;
                    location  / {
                    proxy_pass  http://k8s;
                    proxy_redirect off;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header REMOTE-HOST $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    client_max_body_size 50m;
                    client_body_buffer_size 256k;
                    proxy_connect_timeout 30;
                    proxy_send_timeout 30;
                    proxy_read_timeout 60;
                    proxy_buffer_size 256k;
                    proxy_buffers 4 256k;
                    proxy_busy_buffers_size 256k;
                    proxy_temp_file_write_size 256k;
                    proxy_next_upstream error timeout invalid_header http_500 http_503 http_404;
                    proxy_max_temp_file_size 128m;
                    error_page  404 /var/data/logo/T/404.jpg;
                    error_page  502 /var/data/logo/T/502.png;
                    auth_basic                  "Please Input username/password";
                    auth_basic_user_file        zabbix-password;
                    valid_referers none blocked  server_names *.shileizcc.com  www.shileizcc.com;
            }
            location ~* ^(/viewpage.action|pages/viewpage.action) {
                    return 403;
            }
            location ^~ /.git {
                    return 403;
            }
            location ~*.php {
                    return 403;
            }
    }

    ## mirror
    server  {
                    listen 80;
                    status_zone mirror;
                    server_name mirror.shileizcc.com;
                    location  / {
                    proxy_pass  http://mirror;
                    proxy_redirect off;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header REMOTE-HOST $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    client_max_body_size 50m;
                    client_body_buffer_size 256k;
                    proxy_connect_timeout 30;
                    proxy_send_timeout 30;
                    proxy_read_timeout 60;
                    proxy_buffer_size 256k;
                    proxy_buffers 4 256k;
                    proxy_busy_buffers_size 256k;
                    proxy_temp_file_write_size 256k;
                    proxy_next_upstream error timeout invalid_header http_500 http_503 http_404;
                    proxy_max_temp_file_size 128m;
                    error_page  404 /var/data/logo/T/404.jpg;
                    error_page  502 /var/data/logo/T/502.png;
            }
    }

    server {
            listen 80;
            server_name status.shileizcc.com;
            root /usr/share/nginx/html;
            # Redirect requests for / to /status.html
            location = / {
                return 301 /status.html;
            }
            location = /status.html { }
            # Everything beginning with /status (except for /status.html) is
            # processed by the status handler
            location /status {
                status;
    #            auth_basic                  "Please Input username/password";
    #            auth_basic_user_file        status-password;
            }
    }

    #server {
    #       listen 80;
    #       location ^~ /.well-known/acme-challenge/ {
    #           alias /var/data/challenges/;
    #           try_files $uri =404;
    #       }
    #       location / {
    #           rewrite ^/(.*)$ https://shileizcc.com/$1 permanent;
    #       }
    #}