apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb
  namespace: default
  labels:
    app: cheese
    task: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: mariadb
  template:
    metadata:
      labels:
        app: cheese
        task: mariadb
        version: v0.0.1
    spec:
      nodeSelector:
        role: hotstone.com.cn
      containers:
      - name: mariadb
        image: webhippie/mariadb:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: socket
          containerPort: 3306
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: data
          - mountPath: "/var/lib/backup"
            name: backup
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: MARIADB_ROOT_PASSWORD
          value: "owncloud"
        - name: MARIADB_USERNAME
          value: "owncloud"
        - name: MARIADB_PASSWORD
          value: "owncloud"
        - name: MARIADB_DATABASE
          value: "owncloud"
        - name: MARIADB_MAX_ALLOWED_PACKET
          value: "128M"
        - name: MARIADB_INNODB_LOG_FILE_SIZE
          value: "64M"
        - name: MARIADB_INNODB_LARGE_PREFIX
          value: "ON"
        - name: MARIADB_INNODB_FILE_FORMAT
          value: "Barracuda"
      imagePullSecrets:
        - name: myregistrykey
      volumes:
        - hostPath:
            path: "/var/data/mariadb"
          name: data
        - hostPath:
            path: "/var/data/mariadb_backup"
          name: backup
