apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kodexplorer
  namespace: default
  labels:
    app: cheese
    task: kodexplorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: kodexplorer
  template:
    metadata:
      labels:
        app: cheese
        task: kodexplorer
        version: v0.0.1
    spec:
      nodeSelector:
        role: hotstone.com.cn
      containers:
      - name: kodexplorer
        image: daocloud.io/daocloud/kodexplorer
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
          - mountPath: "/var/www/html/data/User/admin/home/VOLUME"
            name: data
        env:
        - name: TZ
          value: "Asia/Shanghai"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: kodexplorer-data
