apiVersion: v1
kind: Service
metadata:
  name: jira
  namespace: default
spec:
  ports:
   - name: http
     port: 8080
     targetPort: 8080
     protocol: TCP
#   - name: https
#     port: 8000
#     targetPort: 8000
#     protocol: TCP
  selector:
    app: cheese
    task: jira
