apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dzzoffice
  namespace: default
  labels:
    app: cheese
    task: dzzoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: dzzoffice
  template:
    metadata:
      labels:
        app: cheese
        task: dzzoffice
        version: v0.0.1
    spec:
      nodeSelector:
        role: hotstone.com.cn
      containers:
      - name: dzzoffice
        image: slzcc/php:7.1.22-fpm
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9000
        volumeMounts:
          - mountPath: "/data/html"
            name: data
        env:
        - name: TZ
          value: "Asia/Shanghai"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: dzzoffice-data
