apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: limit-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: busybox
  template:
    metadata:
      labels:
        app: cheese
        task:  busybox
        version: v0.0.1
    spec:
            #      nodeSelector:
            #        role: shileizcc.com
      containers:
      - image: slzcc/ansible:demo4
        command:
          - sleep
          - "3600000"
        name: busybox
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: busybox
  namespace: limit-example
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  selector:
   app: cheese
   task: busybox
