apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: default
  labels:
    name: db
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "DB"
spec:
  ports:
   - name: http
     port: 3306
     protocol: TCP 
  selector:
    app: cheese
    task: mysql
