apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
    service: mysql
spec:
  ports:
   - name: tcp
     port: 3306
     protocol: TCP 
  selector:
    app: mysql
