apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
  labels:
    name: mysql
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "MySQL"
spec:
#  clusterIP: None
#  selector:
#    name: mysql
#  type: NodePort
  ports:
   - name: http
     port: 3306
     protocol: TCP 
#     nodePort: 3306
  selector:
    app: cheese
    task: mysql
