apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
#  namespace: kube-system
  namespace: default
  labels:
    name: mysql
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: mysql
  template:
    metadata:
      labels:
        app: cheese
        task: mysql
        version: v0.0.1
    spec:
      nodeSelector:
        role: shileizcc.com
      containers:
       - image: registry.aliyuncs.com/slzcc/mysql-5.6
         name: mysql
         env:
           - name: MYSQL_ROOT_PASSWORD
             value: Chengcheng_slzcc
         ports:
           - containerPort: 3306
         volumeMounts:
         - mountPath: "/var/lib/mysql"
           name: data
         - mountPath: "/etc/mysql/conf.d"
           name: config-volume
      imagePullSecrets:
        - name: myregistrykey
      volumes:
        - hostPath:
            path: "/var/data/mysql"
          name: data
        - name: config-volume
          configMap:
            name: mysql
#        - hostPath:
#            path: "/etc/mysql/my.cnf"
