apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
  labels:
    name: mysql
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        version: v1
    spec:
      containers:
       - image: registry.aliyuncs.com/slzcc/mysql-5.6
         name: mysql
         env:
         - name: MYSQL_ROOT_PASSWORD
           value: Chengcheng_slzcc
         ports:
         - containerPort: 3306
           name: mysql
         volumeMounts:
         - mountPath: "/var/lib/mysql"
           name: data
         - mountPath: "/etc/mysql/conf.d"
           name: config-volume
      volumes:
      - name: data
        hostPath:
          path: "/var/data/mysql"
      - name: config-volume
        configMap:
          name: mysql
