kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-gluster-heketi
  annotations:
    volume.beta.kubernetes.io/storage-class: "gluster-heketi"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

