apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash
#  namespace: kube-system
data:
  logstash.conf: |-
      input {
        udp {
        port => 514
        type => syslog
        codec => json
        }
        tcp {
        port => 514
        type => syslog
        codec => json
        }
      }

      filter {
        if [type] == "syslog" {
          grok {
            match => { "message" => "%{SYSLOG5424PRI}%{NONNEGINT:ver} +(?:%{TIMESTAMP_ISO8601:ts}|-) +(?:%{HOSTNAME:containerid}|-) +(?:%    {NOTSPACE:containername}|-) +(?:%{NOTSPACE:proc}|-) +(?:%{WORD:msgid}|-) +(?:%{SYSLOG5424SD:sd}|-|) +%{GREEDYDATA:msg}" }
          }
          syslog_pri { }
          date {
              match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
          }
          if !("_grokparsefailure" in [tags]) {
              mutate {
                replace => [ "@source_host", "%{syslog_hostname}" ]
                replace => [ "@message", "%{syslog_message}" ]
              }
          }
          mutate {
            remove_field => [ "syslog_hostname", "syslog_message", "syslog_timestamp" ]
          }
        }
      }
      output {
          elasticsearch {
              hosts => ["elasticsearch-logging:9200"]
              index => "k8s-%{type}-%{+YYYY.MM.dd}"
              document_type => "%{type}"
              workers => 1
              flush_size => 20000
              idle_flush_time => 10
              template_overwrite => true
              codec => json
          }
      }
