resolver 10.96.0.10 valid=1s;

upstream wiki {
zone upstrean-wiki 64k;
server  confluence.default.svc.cluster.local service=_http._tcp resolve;
#server  wiki-watermark.default.svc.cluster.local service=_http._tcp resolve;
}

## wiki
server  {
                listen 80;
                status_zone wiki;
                server_name wiki.shileizcc.com;
                location  / {
                proxy_pass  http://wiki;
                proxy_redirect off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header REMOTE-HOST $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                client_max_body_size 50m;
                client_body_buffer_size 256k;
                proxy_connect_timeout 30;
                proxy_send_timeout 30;
                proxy_read_timeout 60;
                proxy_buffer_size 256k;
                proxy_buffers 4 256k;
                proxy_busy_buffers_size 256k;
                proxy_temp_file_write_size 256k;
                proxy_max_temp_file_size 128m;
                error_page  404 /var/data/logo/T/404.jpg;
                error_page  502 /var/data/logo/T/502.png;
#		location /img/ {
#        		image_filter watermark;
#        		image_filter_watermark "/etc/nginx/conf.d/shileizcc.com.watermark.png";
#        		image_filter_watermark_position center-center;
#        		image_filter_jpeg_quality   95;
#        		image_filter_buffer         20M;
#        		image_filter_watermark_width_from 400;
#      			image_filter_watermark_height_from 400;
#		}

#	        location ~* ^.+\.(gif|jpg|png|swf|flv|rar|zip|git)$ {
#        		valid_referers none blocked server_names *.shileizcc.com;
#        		if ($invalid_referer) {
#            			rewrite ^/ https://www.shileizcc.com/T/403.png;
#        		}
#    		}
#		limit_req zone=shileizcc_com burst=12 nodelay;

		#禁止非GET|HEAD|POST方式的抓取
		if ($request_method !~ ^(GET|HEAD|POST)$) {
    			return 403;
		}

		if ($http_user_agent ~* (Scrapy|HttpClient)) {
     			return 403;
		}
        }
}